# Should be sourced from local-ci.sh.
# Not intended to be run directly.

# 1. Sanity check envvars to check that we're not going to clobber a user's
#    task database.
if [ -z "$TASKRC" ]; then
  echo "Cannot run without TASKRC set." >&2
  exit 1
fi
if [ "$(realpath "$TASKRC")" = "$(realpath "$HOME/.taskrc")" ]; then
  echo "Refusing to run with taskrc set to ~/.taskrc. Set TASKRC to something else." >&2
  exit 1
fi
if [ "$(realpath "$TASKDATA")" = "$(realpath "$HOME/.task")" ]; then
  echo "Refusing to run with taskdata set to ~/.task. Set TASKDATA to something else." >&2
  exit 1
fi

# 2. Overwrite config file.
SHA2=
if [ -f "$TASKRC" ]; then
  SHA2=$(sha256sum "$TASKRC" | cut -d' ' -f1)
  mv -T "$TASKRC" "$TASKRC.$SHA2"
fi

cat >"$TASKRC" <<EOF
### This file is produced by local-ci/taskwarrior/init.sh.
### Any direct changes will be overwritten. Do not edit this file.
data.location=$TASKDATA
verbose=

## UDAs

# status in local CI system
uda.ci_status.type=string
uda.ci_status.label=Local CI Status
uda.ci_status.values=unstarted,needsig,success,failed
uda.ci_status.default=unstarted
uda.derivation.type=string
uda.derivation.label=Top-level derivation for commit CI run
uda.claimedby.type=string
uda.claimedby.label=Local CI box which has claimed the job

uda.repo_root.type=string
uda.repo_root.label=Local repo directory

# Commit ID -- for PRs this should be empty.
# For tip commits use the TIP_COMMIT tag.
uda.commit_id.type=string
uda.commit_id.label=git commit ID

# PR data -- for commits these should be blank. (PRs have their own
# tasks, which should depend on PRs).
uda.pr_number.type=numeric
uda.pr_number.label=PR number on Github
uda.pr_title.type=string
uda.pr_title.label=PR title from Github
uda.pr_url.type=string
uda.pr_url.label=URL
uda.pr_author.type=string
uda.pr_author.label=PR author from Github
uda.review_status.type=string
uda.review_status.label=Review Status
uda.review_status.values=unreviewed,needschange,nacked,approved
uda.review_status.default=unreviewed
 
# Reports
report.list.description=Default Task List
report.list.filter=project:local-ci
report.list.columns=uuid.short,modified.age,ci_status,due,description
report.list.labels=UUID,Updated,Status,Date,Description
report.list.sort=start-
EOF

if [ -n "$SHA2" ]; then
  NEW_SHA2=$(sha256sum "$TASKRC" | cut -d' ' -f1)
  if [ "$SHA2" = "$NEW_SHA2" ]; then
    rm -- "$TASKRC.$SHA2"
  else
    echo "Warning: $TASKRC seems to have changed. Replaced and moved old version to $TASKRC.$SHA2" >&2
    echo "This can happen if you change \$TASKRC, \$TASKDATA or the code in local-ci/taskwarrior," >&2
    echo "or if you manually edited $TASKRC." 2>&1
    echo 2>&1
    echo "Continuing after 3 seconds." 2>&1
    sleep 3
  fi
fi

