// SPDX-License-Identifier: GPL-3.0-or-later

use bitcoin_hashes::Sha256;
use std::env;
use std::fmt;
use std::fs;
use std::io;
use std::path::Path;

#[derive(Debug)]
pub enum Error {
    HomeNotSet,
    ShellCreationFailed(xshell::Error),
    IoError(io::Error),
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::HomeNotSet => write!(f, "HOME environment variable not set"),
            Self::ShellCreationFailed(msg) => write!(f, "Failed to create shell: {}", msg),
            Self::IoError(e) => write!(f, "IO error: {}", e),
        }
    }
}

impl std::error::Error for Error {}

impl From<io::Error> for Error {
    fn from(e: io::Error) -> Self {
        Self::IoError(e)
    }
}

fn generate_taskrc_content(taskdata: &str) -> String {
    format!(r#"### This file is produced by local-ci/taskwarrior/init.sh.
### Any direct changes will be overwritten. Do not edit this file.
data.location={}
verbose=

## UDAs

# status in local CI system
uda.ci_status.type=string
uda.ci_status.label=Local CI Status
uda.ci_status.values=unstarted,started,success,failed
uda.ci_status.default=unstarted
uda.merge_status.type=string
uda.merge_status.label=Local CI merge Status
uda.merge_status.values=unstarted,needsig,pushed
uda.merge_status.default=unstarted
uda.derivation.type=string
uda.derivation.label=Top-level derivation for commit CI run
uda.claimedby.type=string
uda.claimedby.label=Local CI box which has claimed the job

uda.repo_root.type=string
uda.repo_root.label=Local repo directory

uda.last_refresh.type=date
uda.last_refresh.label=Time of last refresh against local git repo and Github

# Commit ID -- for PRs this should be empty.
# For tip commits use the TIP_COMMIT tag.
uda.commit_id.type=string
uda.commit_id.label=git commit ID

# PR data -- for commits these should be blank. (PRs have their own
# tasks, which should depend on PRs).
uda.pr_number.type=numeric
uda.pr_number.label=PR number on Github
uda.pr_title.type=string
uda.pr_title.label=PR title from Github
uda.pr_author.type=string
uda.pr_author.label=PR author from Github
uda.review_status.type=string
uda.review_status.label=Review Status
uda.review_status.values=unreviewed,needschange,nacked,approved
uda.review_status.default=unreviewed
uda.review_notes.type=string
uda.review_notes.label=Review Notes

# Merge commit data -- for commits these should be blank
uda.base_commit.type=string
uda.base_commit.label=Base commit ID of merge (first parent of merge)
uda.merge_change_id.type=string
uda.merge_change_id.label=JJ change ID of merge commit

# Reports
report.list.description=Default Task List
report.list.filter=project:local-ci
report.list.columns=uuid.short,modified.age,ci_status,due,description
report.list.labels=UUID,Updated,Status,Date,Description
report.list.sort=start-
"#, taskdata)
}

fn initialize_taskrc(taskrc_path: &Path, taskdata: &str) -> Result<(), Error> {
    let new_content = generate_taskrc_content(taskdata);
    let new_hash = Sha256::hash(new_content.as_bytes());

    // Check if file exists and get its hash
    if taskrc_path.exists() {
        let existing_content = fs::read_to_string(taskrc_path)?;
        let existing_hash = Sha256::hash(existing_content.as_bytes());

        if existing_hash == new_hash {
            // File is already up to date
            return Ok(());
        }

        // Backup existing file
        let backup_path = format!("{}.{}", taskrc_path.display(), existing_hash);
        fs::rename(taskrc_path, &backup_path)?;
        eprintln!("Warning: {} seems to have changed. Replaced and moved old version to
{}",
                  taskrc_path.display(), backup_path);
        eprintln!("This can happen if you change $TASKRC, $TASKDATA or the code in
local-ci/taskwarrior,");
        eprintln!("or if you manually edited {}.", taskrc_path.display());
        eprintln!();
        eprintln!("Continuing after 3 seconds.");
        std::thread::sleep(std::time::Duration::from_secs(3));
    }

    // Write new content
    fs::write(taskrc_path, new_content)?;
    Ok(())
}

pub fn task_shell() -> Result<xshell::Shell, Error> {
    let sh = xshell::Shell::new()
        .map_err(Error::ShellCreationFailed)?;

    // Get HOME directory
    let home = env::var("HOME")
        .map_err(|_| Error::HomeNotSet)?;

    // Set TASKRC and TASKDATA environment variables as done in local-ci.sh
    let taskrc_path = format!("{}/.config/local-ci2.taskrc", home);
    let taskdata_path = format!("{}/.local-ci2.task", home);

    // Initialize TASKRC if needed
    initialize_taskrc(Path::new(&taskrc_path), &taskdata_path)?;

    sh.set_var("TASKRC", &taskrc_path);
    sh.set_var("TASKDATA", &taskdata_path);

    Ok(sh)
}
